# Generated by Django 4.2.7 on 2025-08-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(unique=True)),
                ('adi_soyadi', models.CharField(max_length=255)),
            ],
        ),
    ]
